export enum ImgIconEnum {
  angular = '../assets/img/angular.svg',
  angular_logo = '../assets/img/Angular_Logo_SVG.svg',
  angular_black = '../assets/img/angular_solidBlack.svg',
  css = '../assets/img/css.svg',
  django = '../assets/img/django.svg',
  html = '../assets/img/html.svg',
  java = '../assets/img/java.svg',
  java_black = '../assets/img/java_logo.png',
  javascript = '../assets/img/javascript.svg',
  php = '../assets/img/php.svg',
  python = '../assets/img/python.svg',
  react = '../assets/img/react.svg',
  springBoot = '../assets/img/spring-boot.svg',
  typescript = '../assets/img/typescript.svg',
}
